# Generated by Django 5.1.8 on 2025-05-04 07:37

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('tier', models.IntegerField(choices=[(1, 'Siswa Melati 1'), (2, 'Siswa Melati 2'), (3, 'Siswa Melati 3'), (4, 'Siswa Melati 4'), (5, 'Kader Dasar'), (6, 'Kader Muda'), (7, 'Kader Madya'), (8, 'Kader Kepala'), (9, 'Kader Utama'), (10, 'Pendekar Muda'), (11, 'Pendekar Madya'), (12, 'Pendekar Kepala'), (13, 'Pendekar Utama'), (14, 'Pendekar Besar')], default=1)),
                ('years_of_joining', models.CharField(max_length=4)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.branches')),
            ],
        ),
    ]
