# Generated by Django 5.1.8 on 2025-05-04 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member'},
        ),
        migrations.CreateModel(
            name='IncomingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.IntegerField(choices=[(1, 'Undangan'), (2, 'Surat Keputusan'), (3, 'Surat Perintah'), (4, 'Surat Permohonan'), (5, 'Surat Pemberitahuan'), (6, 'Proposal'), (7, 'Surat Peminjaman')], default=1)),
                ('mail_number', models.CharField(blank=True, max_length=50)),
                ('mail_purpose', models.TextField(blank=True)),
                ('sender', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Incoming Mails',
            },
        ),
        migrations.CreateModel(
            name='OutgoingMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.IntegerField(choices=[(1, 'Undangan'), (2, 'Surat Keputusan'), (3, 'Surat Perintah'), (4, 'Surat Permohonan'), (5, 'Surat Pemberitahuan'), (6, 'Proposal'), (7, 'Surat Peminjaman')], default=1)),
                ('mail_number', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=150)),
                ('recipient', models.CharField(blank=True, max_length=150)),
                ('event_name', models.CharField(max_length=150)),
                ('event_location', models.CharField(blank=True, max_length=150)),
                ('event_Date', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(max_length=80)),
                ('signed_date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Outgoing Mails',
            },
        ),
    ]
