# Generated by Django 5.1.8 on 2025-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
